### ISSUE TITLE
Scope Back-up Tasks Strategy

### ISSUE THREAD

**Issue by cohiggins** [bcgov/moodle#26] opened 2021-07-22 18:47 UTC
- [ ] Document back-up task questions
- [ ] Provide best practice recommendations
- [ ] Jared to review Freshworks for strategy docs we can leverage

**Comment by cohiggins** [comment] 2021-08-25 16:56
Team meeting with Jeremy Vernon to discuss data-backup options on Aug 25.

**Comment by will-freshworks** [comment] 2021-11-02 17:28
Closed as duplicate of #10

**Closed** 2021-11-02 17:29 UTC
